pipeline {
    agent {
        label 'docker-maven-slave'
        /*
        docker {
            image 'maven:3-alpine'
            args '--privileged -v /root/.m2:/root/.m2'
            label 'docker'
        }
        */
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
